spring:
  data:
    mongodb:
      uri: mongodb+srv://admin:Trang123@cluster0.mll6ctp.mongodb.net/flower-shop
  mail:
    host: smtp.gmail.com
    port: 587
    username: blackofwhite55@gmail.com
    password: iilunvtopjcekxcv
    properties:
#      fojc uzjz echg thfv
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  http:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
email:
  reset-url: http://localhost:5000/resetpassword/change-password?userName=
application:
  version: "v1"
  default:
    paging:
      page: 0
      size: 20
upload:
  directory: D:\HKII_23-24\KLTN\Img
vnpay:
  vnp_TmnCode: U39O3AW8
  vnp_HashSecret: VQ4QLLP1FBOFC2X70CQJ9FE4234WKJ9B
  vnp_Url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html\
  vnp_RetUrl: http://localhost:5000/vnpay-return

logback:
  access:
    enabled: false
